- src/parser.ts
- src/stringify.ts
- src/utils.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
before
```tsx
/**
* @example
*   ;<caption>A Script that can fetch the new data</caption>
*
*   const remoteSupportSymbols = await fetch(URL).then(res => res.json())
*
*   globalThis.foo = keyBy(
*     remoteSupportSymbols.filter(value => value.type !== 'option').map(value => camelizeKeys(value)),
*     'symbol',
*   )
*
*   console.info(globalThis.foo)
*/
```
with this PR
```tsx
/**
* @example <caption>A Script that can fetch the new data</caption>
*
*   const remoteSupportSymbols = await fetch(URL).then(res => res.json())
*
*   globalThis.foo = keyBy(
*     remoteSupportSymbols.filter(value => value.type !== 'option').map(value => camelizeKeys(value)),
*     'symbol',
*   )
*
*   console.info(globalThis.foo)
*/
```
> fix: the "caption" should place behind the tag of "example"

- src/parser.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
I noticed that this plugin's latest release has been deleting empty line comments. Fix, with unit test. The unit test does fail if the fix isn't applied.
> fix: keep empty line comments

- README.md
The default value of `jsdocKeepUnParseAbleExampleIndent` was incorrect. The correct value according to the CLI is:
```
--jsdoc-keep-un-parse-able-example-indent
Should unParseAble example (pseudo code or no js code) keep its indentation
Defaults to false.
```
> Updated incorrect default in readme

- src/parser.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
I noticed that the tag type correction could potentially discard part of the "tag".
> fix(parser): tag type correction

- src/parser.ts
- src/types.ts
I wanted to get rid of the `parser: any`, so I did. As it turned out, `JsdocOptions` extended the wrong option type.
> refactor: better types for parser

- src/parser.ts
- src/utils.ts
- tests/__snapshots__/main.test.js.snap
- tests/__snapshots__/modern.test.js.snap
- tests/main.test.js
- tests/modern.test.js
Changes:
- The function is now called `convertToModernType` instead of `convertToModernArray`. This is appropriate because it also converts JSDoc-type generics (`Foo.<Bar>`) to TS generics (`Foo<Bar>`).
- String literals are now accounted for. This means that they are now guaranteed to be unaffected by transformations. Template literal types are not supported, however. If template literal types are detected, the function will immediately return without changing the type as correctness cannot be guaranteed.
- The regex that replaces arrays now supports up to one level of nested generics. E.g. `Array<Foo>` and `Array<Foo<Bar>>` are supported but `Array<Foo<Foo<Bar>>>` is not.
> fix(parser): modern array transformation

- src/parser.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
The JSDoc check had false positives.
The comment `/* foo /** something */` also passed the check.
> fix(parser): jsdoc check

- src/parser.ts
- src/utils.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
- tests/prettierSource/__snapshots__/index.test.js.snap
The syntax for nullable types (e.g `number?` == `?number` == `number | null`) was parsed as the syntax for [optional parameters](https://jsdoc.app/tags-type.html#:~:text=Optional%20parameter) (e.g. `@param {number=} foo` == `@param {number} [foo]`).
```js
/**
* @param {null | string} ignoreContent
* @param {boolean?} withNodeModules
*/
function _createIgnorer(ignoreContent, withNodeModules) {}
```
---
```js
/**
* @param {null | string} ignoreContent
* @param {boolean=} withNodeModules
*/
function _createIgnorer(ignoreContent, withNodeModules) {}
```
> fix(parser): optional parameter types

- src/utils.ts
- tests/__snapshots__/main.test.js.snap
- tests/main.test.js
Rest parameters weren't formatted since `type name = ...T` isn't valid TS.
> feat(type-formatter): support rest parameters

- src/parser.ts
- src/utils.ts
- tests/main.test.js
Windows EOL is now supported.
This is done by replacing whatever the current EOL is with `\n`. This means all of our code can now correctly assume that only `\n` is used. Line ends are converted back to whatever is configured at the end.
---
This fixes #48
> fix: windows EOL now supported

- src/descriptionFormatter.ts
- src/parser.ts
- src/stringify.ts
- tests/__snapshots__/files/prism-core.js.shot
- tests/__snapshots__/files/typeScript.js.shot
- tests/__snapshots__/files/typeScript.ts.shot
- tests/__snapshots__/paragraph.test.js.snap
- tests/__snapshots__/typeScript.test.js.snap
This brings 2 changs:
1. `options.printWidth` is now the only print width. The print width will no longer be calculated by the functions doing the formatting. We now pass a new `options` object into these functions with a reduced `printWidth` instead.
2. Indentation is now calculated by counting the number of spaces and tabs before the comment. This count will then be converted into an indentation width (= indentation in spaces).
However, there is one problem: tabs and spaces are counted in the original text. This means that the calculated indentation will only be correct if the indentation of the comment does not change.
This problem can be seen in `prism-core.js`. All comments gain an additional indentation level which means that the indentation will be calculated incorrectly and …
> fix: indentation and printWidth

- src/descriptionFormatter.ts
- src/parser.ts
- tests/__snapshots__/files/prism-core.js.shot
- tests/__snapshots__/paragraph.test.js.snap
I originally intended to do a little refactoring but I noticed that some tests were fixed after I did some more whitespace timing.
Apart from extracting some behaviour into function and moving things around not much changed.
Changes:
- Synonyms will now be lowercased. E.g. `@ARG` -> `@arg` -> `@param`.
- The tag title, type, name, desc, and default value will now all be initialized to the empty string if undefined. If defined, they will be trimmed.
- `convertCommentDescToDescTag` now supports merging multiple `@description` tags. 
- Since the tag normalization (includes resolving synonyms) is now done before `convertCommentDescToDescTag`, `@desc` tags are now properly supported.
- The names of typeless alignable tags are no longer ignored. This fixes some potential alignment issues.
> fix: better trimming + refactor

- src/parser.ts
Changes:
- Some minor comment changes
- Added return type for `getParamsOrders`
- `getParamsOrders` is not longer for every tag group, it's only called once per comment now.
- I extracted some of the `map` function into two new functions and added documentation.
> refactor: minor changes

- src/utils.ts
- tests/__snapshots__/main.test.ts.snap
- tests/main.test.ts
Closes https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/109
All tests pass I'm not sure if by removing this match in the regexp somethings breaks. Can you confirm on the intent of this part of the regexp @hosseinmd?
Also didn't add any extra tests because wasn't sure how to add an editorconfig in a folder with the test file in the current configuration, however I did test it in a sandbox and seems to be working
> fix: editorconfig indent_style=tab breaking example tag

- README.md
- src/descriptionFormatter.ts
- src/index.ts
- src/types.ts
Hello!
This plugin is exactly what I need, except for one little detail: It runs into some false positives when trying to capitalize descriptions. Rather than adding more exceptions, the only one currently being links starting with `http(s)://`, I propose an option called `jsdocCapitalizeDescription` that would enable users to turn off capitalization altogether.
> feat: add option to turn off capitalization

- src/parser.ts
This should close https://github.com/facebook/jest/issues/12049
Obviously it's not the most ideal - I don't really know of a good way to test this given that it seems very situational :/
It should be possible to make it more TypeScript friendly by breaking the `jsdocParser` function out to the top level so that function overrides could be used to type the parameters, but that would be a larger change.
> fix: support being called as a built-in parser

- package.json
Adds a package description to the `package.json` `description` field, which is currently empty. This will get used all sorts of contexts, the most obvious being in the search results on [npmjs.com](https://www.npmjs.com):
https://www.npmjs.com/search?q=prettier-plugin-jsdoc
After this PR is published a proper description should appear instead of the first characters of the readme.
> fix: add a package description

- src/descriptionFormatter.ts
- tests/__snapshots__/descriptions.test.ts.snap
- tests/__snapshots__/files/prism-core.js.shot
- tests/descriptions.test.ts
Fixes #142
Have also added a test using the sample markdown the Prettier playground uses, to ensure the formatting remains consistent.
> fix: ensure formatting matches Prettier markdown formatter

- src/descriptionFormatter.ts
- tests/__snapshots__/descriptions.test.ts.snap
- tests/descriptions.test.ts
Fixes #148.
Changes referred to https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/86bb75c55f6894b2387f4f6b0de7207df86004ef.
> fix: line breaks inside jsdoc link synonyms

- src/index.ts
This change enables developers to import the Options type in their .prettierrc.js file to assist them in making type checking on Options.
For example,
```ts
// import prettier-plugin-jsdoc Options
/** @type {import('prettier-plugin-jsdoc').Options} } */
const prettierPluginJsdocOptions = {
jsdocCapitalizeDescription: false,
}
// import prettier Options
/** @type {import('prettier').Options} */
const config = {
plugins: ['prettier-plugin-jsdoc'],
...prettierPluginJsdocOptions,
singleAttributePerLine: true,
arrowParens: 'always',
}
```
> chore: export Options to better assist type checking for .prettierrc.js

- src/index.ts
I read through some of the code and found some TypeScript `as` statements that seemed unnecessary. You'll of course decide for yourself if you want to do this change. No changes were done to the runtime JS code.
> chore: remove unnecessary TypeScript `as`

- package.json
I missed it somehow in https://github.com/hosseinmd/prettier-plugin-jsdoc/pull/195
When working in TypeScript project with `moduleResolution` set to `node16`, `nodenext`, or `bundler`, it's impossible to import type `Options` from the package, because its types are resolved to `./dist/types`
https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/a774106d68d4ebfce332059e46321fdecc490591/src/index.ts#L240
> fix: provide correct types path in conditional exports

- src/parser.ts
The function `addDefaultValueToDescription` was appending multiple "Default is ..." notes to the description upon repeated invocations. This issue has been resolved by updating the regular expression to remove all existing occurrences of "Default is ..." before appending the new default value note.
> Fixed duplication of "Default is ..." in documentation comments.

- package.json
- src/index.ts
- src/parser.ts
- src/utils.ts
- yarn.lock
Closes #245.
Plugin crashes with `TypeError: Cannot read properties of undefined (reading 'length')` when using Prettier 3.6.0 due to changes in the AST structure where `ast.tokens` can be `undefined`.
Added defensive checks in two places:
- `parser.ts`: Check if `ast.tokens` exists before calling `findTokenIndex`
- `utils.ts`: Add null/undefined guards in `findTokenIndex` function
- `getParamsOrders`: Handle case when `tokenIndex` is -1
> fix: add compatibility with prettier v3.6.0

- .github/workflows/test.yml
- tests/__snapshots__/files/prism-core.js.shot
- tests/files/prism-core.js
Prettier 3.6 has some rule changes, updated the test flow to match the version.
https://prettier.io/blog/2025/06/23/3.6.0#other-changes
Note: Needs approval for running tests on Github actions.
> test: prettier version bump into 3.6
